version: '3.8'

services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile.local
    command: ["/bin/sh", "-c", 'php artisan serve --host=0.0.0.0']
    volumes:
      - ./app:/usr/app
    ports:
      - 8000:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge